### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by PreFlasH** [Pompeiro/TFT-DSS#4]
Hello, how can I use it in game?

**Comment by PreFlasH** [comment]
I mean, how can I run it without exe file?

**Comment by Pompeiro** [comment]
> I mean, how can I run it without exe file?

Sorry for delay, you need to run TFTDSS.py file. I am using Spyder from Anaconda environment. Also you need to have installed all libraries which are required to run it properly.

**Comment by xosmi** [comment]
I'll just leave this here 🥇 
Generated list of the required libraries :
matplotlib==3.2.2
pandas==1.0.5
opencv_python==4.4.0.44
pywin32==227
selenium==3.141.0
numpy==1.18.5
scikit_fuzzy==0.4.2
easyocr==1.1.9
win32gui==221.6

I also grabbed the operadriver exe from https://github.com/operasoftware/operachromiumdriver/releases and put it in the folder with the scripts, but idk if that's actually needed for it to run.

Also don't forget to swap the commented and uncommented line in the code block at lines 175-185. (the line "wincap = WindowCapture('League of Legends (TM) Client')" should be uncommented) 
Otherwise the script won't actually check for the game client.

**Comment by Pompeiro** [comment]
@xosmi thank you for help. Good job.
Opera webdriver is only for webscraping purposes while u want to get updated championsData.csv file with DataMining.py
